#child.yml
Parameters:
  EC2Instance:
    Type: String
    Default: t2.micro
    Description: 'EC2 instance type, e.g. m1.small, m1.large, etc.'
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access to the web server

Resources:
  myEc2Test:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2Instance
      KeyName: !Ref KeyName
      ImageId: ami-0fc5d935ebf8bc3bc    