Resources:
   SecurityGroup:
     Type: "AWS::EC2::SecurityGroup"
     Properties:
       GroupDescription: Allow port 80 and 22
       GroupName: "Abhi-security"
       SecurityGroupIngress:
         IpProtocol: "tcp"
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
         IpProtocol: "tcp"
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
